# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.migration.version", 14);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1390370482227");
user_pref("datareporting.policy.firstRunTime", "1390284082226");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.main", 104);
user_pref("datareporting.sessions.current.startTime", "1390284082031");
user_pref("datareporting.sessions.current.totalTime", 0);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/Firefox.app/Contents/MacOS/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1387508246000,\"rdfTime\":1387508246000}}}]");
user_pref("extensions.lastAppVersion", "26.0");
user_pref("extensions.lastPlatformVersion", "26.0");
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20131205075310");
user_pref("gecko.mstone", "26.0");
user_pref("marionette.contentListener", false);
user_pref("marionette.defaultPrefs.enabled", true);
user_pref("marionette.defaultPrefs.port", "2828");
user_pref("marionette.force-local", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("toolkit.telemetry.previousBuildID", "20131205075310");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
